// Code generated by "stringer -type=PDUType"; DO NOT EDIT.

package pdutype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConfirmedServiceRequest-0]
	_ = x[UnconfirmedServiceRequest-16]
	_ = x[SimpleAck-32]
	_ = x[ComplexAck-48]
	_ = x[SegmentAck-64]
	_ = x[Error-80]
	_ = x[Reject-96]
	_ = x[Abort-112]
}

const (
	_PDUType_name_0 = "ConfirmedServiceRequest"
	_PDUType_name_1 = "UnconfirmedServiceRequest"
	_PDUType_name_2 = "SimpleAck"
	_PDUType_name_3 = "ComplexAck"
	_PDUType_name_4 = "SegmentAck"
	_PDUType_name_5 = "Error"
	_PDUType_name_6 = "Reject"
	_PDUType_name_7 = "Abort"
)

func (i PDUType) String() string {
	switch {
	case i == 0:
		return _PDUType_name_0
	case i == 16:
		return _PDUType_name_1
	case i == 32:
		return _PDUType_name_2
	case i == 48:
		return _PDUType_name_3
	case i == 64:
		return _PDUType_name_4
	case i == 80:
		return _PDUType_name_5
	case i == 96:
		return _PDUType_name_6
	case i == 112:
		return _PDUType_name_7
	default:
		return "PDUType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
