// Code generated by "stringer -type=ErrorClass"; DO NOT EDIT.

package errorclass

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Device-0]
	_ = x[Object-1]
	_ = x[Property-2]
	_ = x[Resources-3]
	_ = x[Security-4]
	_ = x[Services-5]
	_ = x[VT-6]
	_ = x[Communication-7]
}

const _ErrorClass_name = "DeviceObjectPropertyResourcesSecurityServicesVTCommunication"

var _ErrorClass_index = [...]uint8{0, 6, 12, 20, 29, 37, 45, 47, 60}

func (i ErrorClass) String() string {
	if i >= ErrorClass(len(_ErrorClass_index)-1) {
		return "ErrorClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorClass_name[_ErrorClass_index[i]:_ErrorClass_index[i+1]]
}
