// Code generated by "stringer -type=Reliability"; DO NOT EDIT.

package reliability

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoFaultDetected-0]
	_ = x[NoSensor-1]
	_ = x[OverRange-2]
	_ = x[UnderRange-3]
	_ = x[OpenLoop-4]
	_ = x[ShortedLoop-5]
	_ = x[NoOutput-6]
	_ = x[UnreliableOther-7]
	_ = x[ProcessError-8]
	_ = x[MultiStateFault-9]
	_ = x[ConfigurationError-10]
	_ = x[CommunicationFailure-12]
	_ = x[MemberFault-13]
	_ = x[MonitoredObjectFault-14]
	_ = x[Tripped-15]
	_ = x[LampFailure-16]
	_ = x[ActivationFailure-17]
	_ = x[RenewDHCPFailure-18]
	_ = x[RenewFDRegistrationFailure-19]
	_ = x[RestartAutoNegotiationFailure-20]
	_ = x[RestartFailure-21]
	_ = x[ProprietaryCommandFailure-22]
	_ = x[FaultsListed-23]
	_ = x[ReferenceObjectFault-24]
	_ = x[MultiStateOutOfRange-25]
}

const (
	_Reliability_name_0 = "NoFaultDetectedNoSensorOverRangeUnderRangeOpenLoopShortedLoopNoOutputUnreliableOtherProcessErrorMultiStateFaultConfigurationError"
	_Reliability_name_1 = "CommunicationFailureMemberFaultMonitoredObjectFaultTrippedLampFailureActivationFailureRenewDHCPFailureRenewFDRegistrationFailureRestartAutoNegotiationFailureRestartFailureProprietaryCommandFailureFaultsListedReferenceObjectFaultMultiStateOutOfRange"
)

var (
	_Reliability_index_0 = [...]uint8{0, 15, 23, 32, 42, 50, 61, 69, 84, 96, 111, 129}
	_Reliability_index_1 = [...]uint8{0, 20, 31, 51, 58, 69, 86, 102, 128, 157, 171, 196, 208, 228, 248}
)

func (i Reliability) String() string {
	switch {
	case i <= 10:
		return _Reliability_name_0[_Reliability_index_0[i]:_Reliability_index_0[i+1]]
	case 12 <= i && i <= 25:
		i -= 12
		return _Reliability_name_1[_Reliability_index_1[i]:_Reliability_index_1[i+1]]
	default:
		return "Reliability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
