// Code generated by "stringer -type=LifeSafetyMode"; DO NOT EDIT.

package lifesafetymode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Off-0]
	_ = x[On-1]
	_ = x[Test-2]
	_ = x[Manned-3]
	_ = x[Unmanned-4]
	_ = x[Armed-5]
	_ = x[Disarmed-6]
	_ = x[Prearmed-7]
	_ = x[Slow-8]
	_ = x[Fast-9]
	_ = x[Disconnected-10]
	_ = x[Enabled-11]
	_ = x[Disabled-12]
	_ = x[AutomaticReleaseDisabled-13]
	_ = x[Default-14]
	_ = x[ActivatedOEOAlarm-15]
	_ = x[ActivatedOEOEvacuate-16]
	_ = x[ActivatedOEOPhase1Recall-17]
	_ = x[ActivatedOEOUnavailable-18]
	_ = x[Deactivated-19]
}

const _LifeSafetyMode_name = "OffOnTestMannedUnmannedArmedDisarmedPrearmedSlowFastDisconnectedEnabledDisabledAutomaticReleaseDisabledDefaultActivatedOEOAlarmActivatedOEOEvacuateActivatedOEOPhase1RecallActivatedOEOUnavailableDeactivated"

var _LifeSafetyMode_index = [...]uint8{0, 3, 5, 9, 15, 23, 28, 36, 44, 48, 52, 64, 71, 79, 103, 110, 127, 147, 171, 194, 205}

func (i LifeSafetyMode) String() string {
	if i >= LifeSafetyMode(len(_LifeSafetyMode_index)-1) {
		return "LifeSafetyMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LifeSafetyMode_name[_LifeSafetyMode_index[i]:_LifeSafetyMode_index[i+1]]
}
