// Code generated by "stringer -type=LifeSafetyState"; DO NOT EDIT.

package lifesafetystate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Quiet-0]
	_ = x[PreAlarm-1]
	_ = x[Alarm-2]
	_ = x[Fault-3]
	_ = x[FaultPreAlarm-4]
	_ = x[FaultAlarm-5]
	_ = x[NotReady-6]
	_ = x[Active-7]
	_ = x[Tamper-8]
	_ = x[TestAlarm-9]
	_ = x[TestActive-10]
	_ = x[TestFault-11]
	_ = x[TestFaultAlarm-12]
	_ = x[Holdup-13]
	_ = x[Duress-14]
	_ = x[TamperAlarm-15]
	_ = x[Abnormal-16]
	_ = x[EmergencyPower-17]
	_ = x[Delayed-18]
	_ = x[Blocked-19]
	_ = x[LocalAlarm-20]
	_ = x[GeneralAlarm-21]
	_ = x[Supervisory-22]
	_ = x[TestSupervisory-23]
	_ = x[NonDefaultMode-24]
	_ = x[OEOUnavailable-25]
	_ = x[OEOAlarm-26]
	_ = x[OROPhase1Recall-27]
	_ = x[OEOEvacuate-28]
	_ = x[OEOUnaffected-29]
	_ = x[TestOEOUnavailable-30]
	_ = x[TestOEOAlarm-31]
	_ = x[TestOROPhase1Recall-32]
	_ = x[TestOEOEvacuate-33]
	_ = x[TestOEOUnaffected-34]
}

const _LifeSafetyState_name = "QuietPreAlarmAlarmFaultFaultPreAlarmFaultAlarmNotReadyActiveTamperTestAlarmTestActiveTestFaultTestFaultAlarmHoldupDuressTamperAlarmAbnormalEmergencyPowerDelayedBlockedLocalAlarmGeneralAlarmSupervisoryTestSupervisoryNonDefaultModeOEOUnavailableOEOAlarmOROPhase1RecallOEOEvacuateOEOUnaffectedTestOEOUnavailableTestOEOAlarmTestOROPhase1RecallTestOEOEvacuateTestOEOUnaffected"

var _LifeSafetyState_index = [...]uint16{0, 5, 13, 18, 23, 36, 46, 54, 60, 66, 75, 85, 94, 108, 114, 120, 131, 139, 153, 160, 167, 177, 189, 200, 215, 229, 243, 251, 266, 277, 290, 308, 320, 339, 354, 371}

func (i LifeSafetyState) String() string {
	if i >= LifeSafetyState(len(_LifeSafetyState_index)-1) {
		return "LifeSafetyState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LifeSafetyState_name[_LifeSafetyState_index[i]:_LifeSafetyState_index[i+1]]
}
