// Code generated by "stringer -type=EventState"; DO NOT EDIT.

package eventstate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Normal-0]
	_ = x[Fault-1]
	_ = x[OffNormal-2]
	_ = x[HighLimit-3]
	_ = x[LowLimit-4]
	_ = x[LifeSafetyAlarm-5]
}

const _EventState_name = "NormalFaultOffNormalHighLimitLowLimitLifeSafetyAlarm"

var _EventState_index = [...]uint8{0, 6, 11, 20, 29, 37, 52}

func (i EventState) String() string {
	if i >= EventState(len(_EventState_index)-1) {
		return "EventState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventState_name[_EventState_index[i]:_EventState_index[i+1]]
}
