package engineeringunit

//go:generate stringer -type=EngineeringUnit

// EngineeringUnit represents all values possible for the BACnetEngineeringUnits type.
type EngineeringUnit uint16

const (
	SquareMeters EngineeringUnit = iota
	SquareFeet
	Milliamperes
	Amperes
	Ohms
	Volts
	Kilovolts
	Megavolts
	VoltAmperes
	KilovoltAmperes
	MegavoltAmperes
	VoltAmperesReactive
	KilovoltAmperesReactive
	MegavoltAmperesReactive
	DegreesPhase
	PowerFactor
	Joules
	Kilojoules
	WattHours
	KilowattHours
	Btus
	Therms
	TonHours
	JoulesPerKilogramDryAir
	BtusPerPoundDryAir
	CyclesPerHour
	CyclesPerMinute
	Hertz
	GramsOfWaterPerKilogramDryAir
	PercentRelativeHumidity
	Millimeters
	Meters
	Inches
	Feet
	WattsPerSquareFoot
	WattsPerSquareMeter
	Lumens
	Luxes
	FootCandles
	Kilograms
	PoundsMass
	Tons
	KilogramsPerSecond
	KilogramsPerMinute
	KilogramsPerHour
	PoundsMassPerMinute
	PoundsMassPerHour
	Watts
	Kilowatts
	Megawatts
	BtusPerHour
	Horsepower
	TonsRefrigeration
	Pascals
	Kilopascals
	Bars
	PoundsForcePerSquareInch
	CentimetersOfWater
	InchesOfWater
	MillimetersOfMercury
	CentimetersOfMercury
	InchesOfMercury
	DegreesCelsius
	DegreesKelvin
	DegreesFahrenheit
	DegreeDaysCelsius
	DegreeDaysFahrenheit
	Years
	Months
	Weeks
	Days
	Hours
	Minutes
	Seconds
	MetersPerSecond
	KilometersPerHour
	FeetPerSecond
	FeetPerMinute
	MilesPerHour
	CubicFeet
	CubicMeters
	ImperialGallons
	Liters
	UsGallons
	CubicFeetPerMinute
	CubicMetersPerSecond
	ImperialGallonsPerMinute
	LitersPerSecond
	LitersPerMinute
	UsGallonsPerMinute
	DegreesAngular
	DegreesCelsiusPerHour
	DegreesCelsiusPerMinute
	DegreesFahrenheitPerHour
	DegreesFahrenheitPerMinute
	NoUnits
	PartsPerMillion
	PartsPerBillion
	Percent
	PercentPerSecond
	PerMinute
	PerSecond
	PsiPerDegreeFahrenheit
	Radians
	RevolutionsPerMinute
	Currency1
	Currency2
	Currency3
	Currency4
	Currency5
	Currency6
	Currency7
	Currency8
	Currency9
	Currency10
	SquareInches
	SquareCentimeters
	BtusPerPound
	Centimeters
	PoundsMassPerSecond
	DeltaDegreesFahrenheit
	DeltaDegreesKelvin
	Kilohms
	Megohms
	Millivolts
	KilojoulesPerKilogram
	Megajoules
	JoulesPerDegreeKelvin
	JoulesPerKilogramDegreeKelvin
	Kilohertz
	Megahertz
	PerHour
	Milliwatts
	Hectopascals
	Millibars
	CubicMetersPerHour
	LitersPerHour
	KilowattHoursPerSquareMeter
	KilowattHoursPerSquareFoot
	MegajoulesPerSquareMeter
	MegajoulesPerSquareFoot
	WattsPerSquareMeterDegreeKelvin
	CubicFeetPerSecond
	PercentObscurationPerFoot
	PercentObscurationPerMeter
	Milliohms
	MegawattHours
	KiloBtus
	MegaBtus
	KilojoulesPerKilogramDryAir
	MegajoulesPerKilogramDryAir
	KilojoulesPerDegreeKelvin
	MegajoulesPerDegreeKelvin
	Newton
	GramsPerSecond
	GramsPerMinute
	TonsPerHour
	KiloBtusPerHour
	HundredthsSeconds
	Milliseconds
	NewtonMeters
	MillimetersPerSecond
	MillimetersPerMinute
	MetersPerMinute
	MetersPerHour
	CubicMetersPerMinute
	MetersPerSecondPerSecond
	AmperesPerMeter
	AmperesPerSquareMeter
	AmpereSquareMeters
	Farads
	Henrys
	OhmMeters
	Siemens
	SiemensPerMeter
	Teslas
	VoltsPerDegreeKelvin
	VoltsPerMeter
	Webers
	Candelas
	CandelasPerSquareMeter
	DegreesKelvinPerHour
	DegreesKelvinPerMinute
	JouleSeconds
	RadiansPerSecond
	SquareMetersPerNewton
	KilogramsPerCubicMeter
	NewtonSeconds
	NewtonsPerMeter
	WattsPerMeterPerDegreeKelvin
	MicroSiemens
	CubicFeetPerHour
	UsGallonsPerHour
	Kilometers
	Micrometers
	Grams
	Milligrams
	Milliliters
	MillilitersPerSecond
	Decibels
	DecibelsMillivolt
	DecibelsVolt
	Millisiemens
	WattHoursReactive
	KilowattHoursReactive
	MegawattHoursReactive
	MillimetersOfWater
	PerMille
	GramsPerGram
	KilogramsPerKilogram
	GramsPerKilogram
	MilligramsPerGram
	MilligramsPerKilogram
	GramsPerMilliliter
	GramsPerLiter
	MilligramsPerLiter
	MicrogramsPerLiter
	GramsPerCubicMeter
	MilligramsPerCubicMeter
	MicrogramsPerCubicMeter
	NanogramsPerCubicMeter
	GramsPerCubicCentimeter
	Becquerels
	Kilobecquerels
	Megabecquerels
	Gray
	Milligray
	Microgray
	Sieverts
	Millisieverts
	Microsieverts
	MicrosievertsPerHour
	DecibelsA
	NephelometricTurbidityUnit
	PH
	GramsPerSquareMeter
	MinutesPerDegreeKelvin
	OhmMeterSquaredPerMeter
	AmpereSeconds
	VoltAmpereHours
	KilovoltAmpereHours
	MegavoltAmpereHours
	VoltAmpereHoursReactive
	KilovoltAmpereHoursReactive
	MegavoltAmpereHoursReactive
	VoltSquareHours
	AmpereSquareHours
	JoulePerHours
	CubicFeetPerDay
	CubicMetersPerDay
	WattHoursPerCubicMeter
	JoulesPerCubicMeter
	MolePercent
	PascalSeconds
	MillionStandardCubicFeetPerMinute
	_
)
const (
	StandardCubicFeetPerDay EngineeringUnit = iota + 47808
	MillionStandardCubicFeetPerDay
	ThousandCubicFeetPerDay
	ThousandStandardCubicFeetPerDay
	PoundsMassPerDay
	_
	Millirems
	MilliremsPerHour
	DegreesLovibond
	AlcoholByVolume
	InternationalBitteringUnits
	EuropeanBitternessUnits
	DegreesPlato
	SpecificGravity
	EuropeanBrewingConvention
)

func (e EngineeringUnit) IsSpecified() bool {
	return (e <= 254 || e >= 47808 && e <= 47822) &&
		e != 47813
}

func (e EngineeringUnit) IsReserved() bool {
	return e <= 255 || e >= 47808 && e <= 49999
}

func (e EngineeringUnit) IsExtension() bool {
	return !e.IsReserved()
}
